# Generated by Django 2.2.12 on 2025-03-28 13:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo_inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('precio', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('marca', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Catalogo inventario',
                'verbose_name_plural': 'Catalogo inventarios',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metodo_pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('disponibilidad', models.CharField(choices=[('SI', 'Disponible'), ('NO', 'No Disponible')], default='SI', max_length=2)),
            ],
            options={
                'verbose_name': 'Metodo Pago',
                'verbose_name_plural': 'Metodos de pago',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('catalogoProductos', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('apellido', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('celular', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=120, null=True)),
                ('rol', models.IntegerField(choices=[(1, 'Empleados'), (2, 'Clientes')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(upload_to='')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=120)),
                ('precio', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('disponibilidad', models.CharField(choices=[('SI', 'Disponible'), ('NO', 'No Disponible')], default='SI', max_length=2)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk1_producto_categoria', to='PanaderiasMaye.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk5_detalle_carrito_producto', to='PanaderiasMaye.Producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk6_entrada_proveedor', to='PanaderiasMaye.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('total', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('servicio', models.CharField(max_length=150)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk2_detalle_carrito_producto', to='PanaderiasMaye.Producto')),
            ],
            options={
                'verbose_name': 'Detalle Carrito',
                'verbose_name_plural': 'Detalle Del Carrito',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('total', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('servicio', models.CharField(max_length=150)),
                ('Detalle_carrito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk4_carrito_detalleCarrito', to='PanaderiasMaye.Detalle_carrito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk3_carrito_usuario', to='PanaderiasMaye.User')),
            ],
        ),
    ]
