# Generated by Django 5.1.7 on 2025-03-10 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('total', models.FloatField()),
                ('servicio', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Detalle Carrito',
                'verbose_name_plural': 'Detalle Del Carrito',
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Metodo_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('disponibilidad', models.CharField(choices=[('SI', 'Disponible'), ('NO', 'No Disponible')], default='SI', max_length=2)),
            ],
            options={
                'verbose_name': 'Metodo Pago',
                'verbose_name_plural': 'Metodo de pago',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('catalogoProductos', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=2)),
                ('rol', models.IntegerField(choices=[(1, 'Empleados'), (2, 'Clientes')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('total', models.FloatField()),
                ('servicio', models.CharField(max_length=150)),
                ('Detalle_carrito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk5_carrito_detalleCarrito', to='PanaderiasMaye.detalle_carrito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk4_carrito_usuario', to='PanaderiasMaye.user')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk7_factura_carrito', to='PanaderiasMaye.carrito')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk8_factura_metodo_pago', to='PanaderiasMaye.metodo_pago')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('total', models.FloatField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk9_detalle_factura_factura', to='PanaderiasMaye.factura')),
            ],
            options={
                'verbose_name': 'Detalle Factura',
                'verbose_name_plural': 'Detalle de Factura',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=120)),
                ('precio', models.FloatField()),
                ('disponibilidad', models.CharField(choices=[('SI', 'Disponible'), ('NO', 'No Disponible')], default='SI', max_length=2)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk1_producto_categoria', to='PanaderiasMaye.categoria')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk2_producto_entrada', to='PanaderiasMaye.entrada')),
            ],
        ),
        migrations.AddField(
            model_name='detalle_carrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk3_detalle_carrito_producto', to='PanaderiasMaye.producto'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk6_entrada_proveedor', to='PanaderiasMaye.proveedor'),
        ),
    ]
