# Generated by Django 5.1.7 on 2025-03-13 03:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanaderiasMaye', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo_inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('precio', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('marca', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Catalogo inventario',
                'verbose_name_plural': 'Catalogo inventarios',
            },
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='metodo_pago',
        ),
        migrations.AlterModelOptions(
            name='metodo_pago',
            options={'verbose_name': 'Metodo Pago', 'verbose_name_plural': 'Metodos de pago'},
        ),
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrito',
            name='Detalle_carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk4_carrito_detalleCarrito', to='PanaderiasMaye.detalle_carrito'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='total',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk3_carrito_usuario', to='PanaderiasMaye.user'),
        ),
        migrations.AlterField(
            model_name='detalle_carrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk2_detalle_carrito_producto', to='PanaderiasMaye.producto'),
        ),
        migrations.AlterField(
            model_name='detalle_carrito',
            name='total',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='apellido',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk5_detalle_carrito_producto', to='PanaderiasMaye.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk6_entrada_proveedor', to='PanaderiasMaye.proveedor')),
            ],
        ),
        migrations.DeleteModel(
            name='Detalle_factura',
        ),
        migrations.DeleteModel(
            name='Entrada',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
