# Generated by Django 4.0.6 on 2025-03-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanaderiasMaye', '0002_catalogo_inventario_remove_entrada_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='direccion',
            field=models.CharField(max_length=120),
        ),
    ]
