# Generated by Django 2.2.12 on 2025-03-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanaderiasMaye', '0003_auto_20250331_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='usuarios/default.png', max_length=254, upload_to='usuarios'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(max_length=254, upload_to='usuarios'),
        ),
    ]
