# Generated by Django 4.0.6 on 2025-04-01 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PanaderiasMaye', '0005_remove_user_direccion_alter_carrito_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='total',
        ),
        migrations.RemoveField(
            model_name='detalle_carrito',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='foto',
        ),
        migrations.AddField(
            model_name='carrito',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='servicio',
            field=models.IntegerField(choices=[(1, 'Domicilio'), (2, 'Reserva')], default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
