# Generated by Django 4.0.6 on 2025-04-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanaderiasMaye', '0006_remove_carrito_total_remove_detalle_carrito_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='usuarios/default.jpg', upload_to='usuarios'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default='productos/pan9.jpeg', upload_to='productos'),
        ),
    ]
