# Generated by Django 4.0.6 on 2025-04-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanaderiasMaye', '0007_user_foto_alter_producto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Pagado')], default=1),
        ),
    ]
