# Generated by Django 5.1.6 on 2025-04-04 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanaderiasMaye', '0008_carrito_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='Detalle_carrito',
        ),
        migrations.AddField(
            model_name='detalle_carrito',
            name='carrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='PanaderiasMaye.carrito'),
        ),
    ]
