# Generated by Django 5.1.6 on 2025-04-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanaderiasMaye', '0009_remove_carrito_detalle_carrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='meotdo_pago',
            field=models.IntegerField(choices=[(1, 'Nequi'), (2, 'Bancolombia'), (3, 'Tarjeta de Crédito'), (4, 'Efectivo')], default=4),
        ),
    ]
