# Generated by Django 5.1.6 on 2025-04-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PanaderiasMaye', '0010_carrito_meotdo_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='meotdo_pago',
            new_name='metodo_pago',
        ),
    ]
