# Generated by Django 5.1.7 on 2025-04-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanaderiasMaye', '0011_rename_meotdo_pago_carrito_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=100),
        ),
    ]
