# Generated by Django 4.0.6 on 2025-04-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanaderiasMaye', '0012_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='fecha_reserva',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='carrito',
            name='nombre_destinatario',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
