# Generated by Django 5.2 on 2025-04-17 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PanaderiasMaye', '0015_user_token_user_verificado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'get_latest_by': 'fecha'},
        ),
    ]
