# Generated by Django 5.2 on 2025-04-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanaderiasMaye', '0016_alter_carrito_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='direccion',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='carrito',
            name='especificaciones_direccion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'reservado'), (2, 'Pagado')], default=1),
        ),
    ]
