# Generated by Django 5.2 on 2025-04-29 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanaderiasMaye', '0017_carrito_direccion_carrito_especificaciones_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='metodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk6_carrito_metodo_pago', to='PanaderiasMaye.metodo_pago'),
        ),
    ]
