# Generated by Django 5.2 on 2025-04-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanaderiasMaye', '0020_alter_carrito_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='metodo_pago',
            field=models.IntegerField(choices=[(1, 'Nequi'), (2, 'Bancolombia'), (3, 'Tarjeta de Crédito'), (4, 'Efectivo')], default=4),
        ),
    ]
