# Generated by Django 5.2 on 2025-05-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanaderiasMaye', '0023_alter_carrito_metodo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pqrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=224)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
