# Generated by Django 5.2 on 2025-05-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanaderiasMaye', '0024_pqrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Petición'), (2, 'Queja'), (3, 'Reclamo'), (4, 'Sugerencia'), (5, 'Felicitación')], default=1),
        ),
    ]
