# Generated by Django 4.2.7 on 2025-05-02 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PanaderiasMaye', '0025_pqrs_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_carrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk4_detalle_carrito_producto', to='PanaderiasMaye.producto'),
        ),
    ]
